/**
 * EdgeOS migration · Step 3 — Load
 *
 * Emits a single transactional SQL file from .migration/ready/load.json.
 *
 *   node scripts/migrate/03-load.js --in .migration/ready --out .migration/load.sql
 *   psql "$SUPABASE_DB_URL" -v ON_ERROR_STOP=1 -f .migration/load.sql
 *
 * Properties that matter:
 *  · One transaction. A partial migration is worse than none.
 *  · Idempotent — ON CONFLICT DO NOTHING keyed on the uuids 02-transform
 *    assigned deterministically, so a failed run can simply be re-run.
 *  · FK-ordered.
 *  · Triggers are left ENABLED so line-item totals, usage counters and
 *    amount_paid are computed by the database, exactly as they will be in
 *    production. The recomputed totals are then diffed against Firebase's
 *    stored values by 04-verify.js.
 *
 * Storage objects are uploaded separately from assets.json; run
 * 03b-upload-assets.js with the service-role key.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

// FK-safe order.
const ORDER = [
  'organizations', 'org_banking', 'org_secrets', 'org_settings', 'subscriptions',
  'memberships', 'departments', 'employees', 'employee_compensation',
  'customers', 'crm_leads', 'products', 'expenses', 'tasks',
  'records', 'financial_documents', 'document_line_items', 'payments',
  'recurring_invoices', 'document_signatures', 'notifications', 'ai_company_memory',
];

// Columns that must not reach SQL (diagnostics carried by the transform).
const INTERNAL = new Set(['_firebase_totals', '_legacy']);

const q = (v) => {
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'null';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (Array.isArray(v) && v.every(x => typeof x === 'string')) {
    return v.length === 0 ? "'{}'" : `array[${v.map(s => q(s)).join(',')}]::text[]`;
  }
  if (typeof v === 'object') return `${q(JSON.stringify(v))}::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
};

function insertStatements(table, rows) {
  if (!rows.length) return '';
  const cols = [...new Set(rows.flatMap(Object.keys))].filter(c => !INTERNAL.has(c));
  const chunks = [];
  for (let i = 0; i < rows.length; i += 500) {
    const values = rows.slice(i, i + 500)
      .map(r => `  (${cols.map(c => q(r[c] ?? null)).join(', ')})`)
      .join(',\n');
    chunks.push(
      `insert into public.${table} (${cols.join(', ')}) values\n${values}\n` +
      `on conflict do nothing;`
    );
  }
  return `-- ${table}: ${rows.length} row(s)\n${chunks.join('\n')}\n`;
}

function main() {
  const args = Object.fromEntries(process.argv.slice(2).flatMap((a, i, arr) =>
    a.startsWith('--') ? [[a.slice(2), arr[i + 1]]] : []));
  const inDir = args.in ?? '.migration/ready';
  const outFile = args.out ?? '.migration/load.sql';

  const data = JSON.parse(readFileSync(join(inDir, 'load.json'), 'utf8'));
  const idRows = JSON.parse(readFileSync(join(inDir, 'legacy_id_map.json'), 'utf8'));

  const sql = [
    '-- EdgeOS Firebase -> Supabase data load.',
    '-- Generated by scripts/migrate/03-load.js. Do not edit by hand.',
    '-- Single transaction: it either all lands or none of it does.',
    '',
    'begin;',
    '',
    "set local statement_timeout = '30min';",
    '',
  ];

  for (const table of ORDER) {
    const rows = data[table] ?? [];
    if (rows.length) sql.push(insertStatements(table, rows));
  }

  sql.push(insertStatements('legacy_id_map', idRows));

  sql.push(`
-- Push every document counter past the highest imported number so newly
-- created documents cannot collide with migrated ones.
select app.reseed_document_counters();

-- Recount usage from the loaded rows rather than trusting the trigger deltas.
select app.rebuild_usage_counters();

commit;

-- ── Post-load summary ───────────────────────────────────────────────────────
\\echo ''
\\echo 'Loaded:'
select 'organizations'        as table, count(*) from organizations
union all select 'memberships',          count(*) from memberships
union all select 'employees',            count(*) from employees
union all select 'departments',          count(*) from departments
union all select 'customers',            count(*) from customers
union all select 'records',              count(*) from records
union all select 'financial_documents',  count(*) from financial_documents
union all select 'document_line_items',  count(*) from document_line_items
union all select 'payments',             count(*) from payments
union all select 'recurring_invoices',   count(*) from recurring_invoices
union all select 'tasks',                count(*) from tasks
union all select 'crm_leads',            count(*) from crm_leads
union all select 'products',             count(*) from products
union all select 'expenses',             count(*) from expenses
union all select 'notifications',        count(*) from notifications
union all select 'document_signatures',  count(*) from document_signatures
order by 1;
`);

  writeFileSync(outFile, sql.join('\n'));
  const total = ORDER.reduce((n, t) => n + (data[t]?.length ?? 0), 0);
  console.log(`\n  Wrote ${outFile}`);
  console.log(`  ${total} rows across ${ORDER.filter(t => data[t]?.length).length} tables`);
  console.log(`  ${idRows.length} legacy id mappings\n`);
  console.log(`  Next:  psql "$SUPABASE_DB_URL" -v ON_ERROR_STOP=1 -f ${outFile}\n`);
}

main();
