-- ============================================================================
-- EdgeOS · 0012_country_codes.sql
--
-- GENERATED FILE — do not edit by hand.
-- Regenerate with:  node scripts/generate-country-seed.js
--
-- ISO 3166-1 alpha-2, from the i18n-iso-countries package. This is reference
-- data, not tenant data: one row per country, shared by every organisation,
-- readable by anyone signed in and writable by no one.
--
-- It earns its place twice over:
--   1. `aliases` makes organizations.country, a free-text field somebody typed
--      during registration ("India", "USA", "United States"), resolvable to a
--      code without a pile of guesswork in a CASE expression.
--   2. country_code columns get a foreign key, so a typo cannot become a
--      country that the map has no shape for and no report can explain.
-- ============================================================================

create table country_codes (
  code    char(2) primary key check (code ~ '^[A-Z]{2}$'),
  name    text not null,
  aliases text[] not null default '{}'
);

insert into country_codes (code, name, aliases) values
  ('AD', 'Andorra', array['Andorra']),
  ('AE', 'United Arab Emirates', array['United Arab Emirates', 'UAE']),
  ('AF', 'Afghanistan', array['Afghanistan']),
  ('AG', 'Antigua and Barbuda', array['Antigua and Barbuda']),
  ('AI', 'Anguilla', array['Anguilla']),
  ('AL', 'Albania', array['Albania']),
  ('AM', 'Armenia', array['Armenia']),
  ('AO', 'Angola', array['Angola']),
  ('AQ', 'Antarctica', array['Antarctica']),
  ('AR', 'Argentina', array['Argentina']),
  ('AS', 'American Samoa', array['American Samoa']),
  ('AT', 'Austria', array['Austria']),
  ('AU', 'Australia', array['Australia']),
  ('AW', 'Aruba', array['Aruba']),
  ('AX', 'Åland Islands', array['Åland Islands', 'Aland Islands']),
  ('AZ', 'Azerbaijan', array['Azerbaijan']),
  ('BA', 'Bosnia and Herzegovina', array['Bosnia and Herzegovina']),
  ('BB', 'Barbados', array['Barbados']),
  ('BD', 'Bangladesh', array['Bangladesh']),
  ('BE', 'Belgium', array['Belgium']),
  ('BF', 'Burkina Faso', array['Burkina Faso']),
  ('BG', 'Bulgaria', array['Bulgaria']),
  ('BH', 'Bahrain', array['Bahrain']),
  ('BI', 'Burundi', array['Burundi']),
  ('BJ', 'Benin', array['Benin']),
  ('BL', 'Saint Barthélemy', array['Saint Barthélemy']),
  ('BM', 'Bermuda', array['Bermuda']),
  ('BN', 'Brunei Darussalam', array['Brunei Darussalam']),
  ('BO', 'Bolivia', array['Bolivia']),
  ('BQ', 'Bonaire, Sint Eustatius and Saba', array['Bonaire, Sint Eustatius and Saba']),
  ('BR', 'Brazil', array['Brazil']),
  ('BS', 'Bahamas', array['Bahamas']),
  ('BT', 'Bhutan', array['Bhutan']),
  ('BV', 'Bouvet Island', array['Bouvet Island']),
  ('BW', 'Botswana', array['Botswana']),
  ('BY', 'Belarus', array['Belarus']),
  ('BZ', 'Belize', array['Belize']),
  ('CA', 'Canada', array['Canada']),
  ('CC', 'Cocos (Keeling) Islands', array['Cocos (Keeling) Islands']),
  ('CD', 'Democratic Republic of the Congo', array['Democratic Republic of the Congo', 'Congo']),
  ('CF', 'Central African Republic', array['Central African Republic']),
  ('CG', 'Republic of the Congo', array['Republic of the Congo', 'Congo']),
  ('CH', 'Switzerland', array['Switzerland']),
  ('CI', 'Cote d''Ivoire', array['Cote d''Ivoire', 'Côte d''Ivoire', 'Ivory Coast']),
  ('CK', 'Cook Islands', array['Cook Islands']),
  ('CL', 'Chile', array['Chile']),
  ('CM', 'Cameroon', array['Cameroon']),
  ('CN', 'People''s Republic of China', array['People''s Republic of China', 'China']),
  ('CO', 'Colombia', array['Colombia']),
  ('CR', 'Costa Rica', array['Costa Rica']),
  ('CU', 'Cuba', array['Cuba']),
  ('CV', 'Cape Verde', array['Cape Verde']),
  ('CW', 'Curaçao', array['Curaçao']),
  ('CX', 'Christmas Island', array['Christmas Island']),
  ('CY', 'Cyprus', array['Cyprus']),
  ('CZ', 'Czech Republic', array['Czech Republic', 'Czechia']),
  ('DE', 'Germany', array['Germany']),
  ('DJ', 'Djibouti', array['Djibouti']),
  ('DK', 'Denmark', array['Denmark']),
  ('DM', 'Dominica', array['Dominica']),
  ('DO', 'Dominican Republic', array['Dominican Republic']),
  ('DZ', 'Algeria', array['Algeria']),
  ('EC', 'Ecuador', array['Ecuador']),
  ('EE', 'Estonia', array['Estonia']),
  ('EG', 'Egypt', array['Egypt']),
  ('EH', 'Western Sahara', array['Western Sahara']),
  ('ER', 'Eritrea', array['Eritrea']),
  ('ES', 'Spain', array['Spain']),
  ('ET', 'Ethiopia', array['Ethiopia']),
  ('FI', 'Finland', array['Finland']),
  ('FJ', 'Fiji', array['Fiji']),
  ('FK', 'Falkland Islands (Malvinas)', array['Falkland Islands (Malvinas)']),
  ('FM', 'Micronesia, Federated States of', array['Micronesia, Federated States of']),
  ('FO', 'Faroe Islands', array['Faroe Islands']),
  ('FR', 'France', array['France']),
  ('GA', 'Gabon', array['Gabon']),
  ('GB', 'United Kingdom', array['United Kingdom', 'UK', 'Great Britain']),
  ('GD', 'Grenada', array['Grenada']),
  ('GE', 'Georgia', array['Georgia']),
  ('GF', 'French Guiana', array['French Guiana']),
  ('GG', 'Guernsey', array['Guernsey']),
  ('GH', 'Ghana', array['Ghana']),
  ('GI', 'Gibraltar', array['Gibraltar']),
  ('GL', 'Greenland', array['Greenland']),
  ('GM', 'Republic of The Gambia', array['Republic of The Gambia', 'The Gambia', 'Gambia']),
  ('GN', 'Guinea', array['Guinea']),
  ('GP', 'Guadeloupe', array['Guadeloupe']),
  ('GQ', 'Equatorial Guinea', array['Equatorial Guinea']),
  ('GR', 'Greece', array['Greece']),
  ('GS', 'South Georgia and the South Sandwich Islands', array['South Georgia and the South Sandwich Islands']),
  ('GT', 'Guatemala', array['Guatemala']),
  ('GU', 'Guam', array['Guam']),
  ('GW', 'Guinea-Bissau', array['Guinea-Bissau']),
  ('GY', 'Guyana', array['Guyana']),
  ('HK', 'Hong Kong', array['Hong Kong']),
  ('HM', 'Heard Island and McDonald Islands', array['Heard Island and McDonald Islands']),
  ('HN', 'Honduras', array['Honduras']),
  ('HR', 'Croatia', array['Croatia']),
  ('HT', 'Haiti', array['Haiti']),
  ('HU', 'Hungary', array['Hungary']),
  ('ID', 'Indonesia', array['Indonesia']),
  ('IE', 'Ireland', array['Ireland']),
  ('IL', 'Israel', array['Israel']),
  ('IM', 'Isle of Man', array['Isle of Man']),
  ('IN', 'India', array['India']),
  ('IO', 'British Indian Ocean Territory', array['British Indian Ocean Territory']),
  ('IQ', 'Iraq', array['Iraq']),
  ('IR', 'Islamic Republic of Iran', array['Islamic Republic of Iran', 'Iran']),
  ('IS', 'Iceland', array['Iceland']),
  ('IT', 'Italy', array['Italy']),
  ('JE', 'Jersey', array['Jersey']),
  ('JM', 'Jamaica', array['Jamaica']),
  ('JO', 'Jordan', array['Jordan']),
  ('JP', 'Japan', array['Japan']),
  ('KE', 'Kenya', array['Kenya']),
  ('KG', 'Kyrgyzstan', array['Kyrgyzstan']),
  ('KH', 'Cambodia', array['Cambodia']),
  ('KI', 'Kiribati', array['Kiribati']),
  ('KM', 'Comoros', array['Comoros']),
  ('KN', 'Saint Kitts and Nevis', array['Saint Kitts and Nevis']),
  ('KP', 'North Korea', array['North Korea']),
  ('KR', 'South Korea', array['South Korea', 'Korea, Republic of', 'Republic of Korea']),
  ('KW', 'Kuwait', array['Kuwait']),
  ('KY', 'Cayman Islands', array['Cayman Islands']),
  ('KZ', 'Kazakhstan', array['Kazakhstan']),
  ('LA', 'Lao People''s Democratic Republic', array['Lao People''s Democratic Republic']),
  ('LB', 'Lebanon', array['Lebanon']),
  ('LC', 'Saint Lucia', array['Saint Lucia']),
  ('LI', 'Liechtenstein', array['Liechtenstein']),
  ('LK', 'Sri Lanka', array['Sri Lanka']),
  ('LR', 'Liberia', array['Liberia']),
  ('LS', 'Lesotho', array['Lesotho']),
  ('LT', 'Lithuania', array['Lithuania']),
  ('LU', 'Luxembourg', array['Luxembourg']),
  ('LV', 'Latvia', array['Latvia']),
  ('LY', 'Libya', array['Libya']),
  ('MA', 'Morocco', array['Morocco']),
  ('MC', 'Monaco', array['Monaco']),
  ('MD', 'Moldova, Republic of', array['Moldova, Republic of']),
  ('ME', 'Montenegro', array['Montenegro']),
  ('MF', 'Saint Martin (French part)', array['Saint Martin (French part)']),
  ('MG', 'Madagascar', array['Madagascar']),
  ('MH', 'Marshall Islands', array['Marshall Islands']),
  ('MK', 'The Republic of North Macedonia', array['The Republic of North Macedonia', 'North Macedonia']),
  ('ML', 'Mali', array['Mali']),
  ('MM', 'Myanmar', array['Myanmar']),
  ('MN', 'Mongolia', array['Mongolia']),
  ('MO', 'Macao', array['Macao']),
  ('MP', 'Northern Mariana Islands', array['Northern Mariana Islands']),
  ('MQ', 'Martinique', array['Martinique']),
  ('MR', 'Mauritania', array['Mauritania']),
  ('MS', 'Montserrat', array['Montserrat']),
  ('MT', 'Malta', array['Malta']),
  ('MU', 'Mauritius', array['Mauritius']),
  ('MV', 'Maldives', array['Maldives']),
  ('MW', 'Malawi', array['Malawi']),
  ('MX', 'Mexico', array['Mexico']),
  ('MY', 'Malaysia', array['Malaysia']),
  ('MZ', 'Mozambique', array['Mozambique']),
  ('NA', 'Namibia', array['Namibia']),
  ('NC', 'New Caledonia', array['New Caledonia']),
  ('NE', 'Niger', array['Niger']),
  ('NF', 'Norfolk Island', array['Norfolk Island']),
  ('NG', 'Nigeria', array['Nigeria']),
  ('NI', 'Nicaragua', array['Nicaragua']),
  ('NL', 'Netherlands', array['Netherlands', 'The Netherlands', 'Netherlands (Kingdom of the)']),
  ('NO', 'Norway', array['Norway']),
  ('NP', 'Nepal', array['Nepal']),
  ('NR', 'Nauru', array['Nauru']),
  ('NU', 'Niue', array['Niue']),
  ('NZ', 'New Zealand', array['New Zealand']),
  ('OM', 'Oman', array['Oman']),
  ('PA', 'Panama', array['Panama']),
  ('PE', 'Peru', array['Peru']),
  ('PF', 'French Polynesia', array['French Polynesia']),
  ('PG', 'Papua New Guinea', array['Papua New Guinea']),
  ('PH', 'Philippines', array['Philippines']),
  ('PK', 'Pakistan', array['Pakistan']),
  ('PL', 'Poland', array['Poland']),
  ('PM', 'Saint Pierre and Miquelon', array['Saint Pierre and Miquelon']),
  ('PN', 'Pitcairn', array['Pitcairn', 'Pitcairn Islands']),
  ('PR', 'Puerto Rico', array['Puerto Rico']),
  ('PS', 'State of Palestine', array['State of Palestine', 'Palestine']),
  ('PT', 'Portugal', array['Portugal']),
  ('PW', 'Palau', array['Palau']),
  ('PY', 'Paraguay', array['Paraguay']),
  ('QA', 'Qatar', array['Qatar']),
  ('RE', 'Reunion', array['Reunion']),
  ('RO', 'Romania', array['Romania']),
  ('RS', 'Serbia', array['Serbia']),
  ('RU', 'Russian Federation', array['Russian Federation', 'Russia']),
  ('RW', 'Rwanda', array['Rwanda']),
  ('SA', 'Saudi Arabia', array['Saudi Arabia']),
  ('SB', 'Solomon Islands', array['Solomon Islands']),
  ('SC', 'Seychelles', array['Seychelles']),
  ('SD', 'Sudan', array['Sudan']),
  ('SE', 'Sweden', array['Sweden']),
  ('SG', 'Singapore', array['Singapore']),
  ('SH', 'Saint Helena', array['Saint Helena']),
  ('SI', 'Slovenia', array['Slovenia']),
  ('SJ', 'Svalbard and Jan Mayen', array['Svalbard and Jan Mayen']),
  ('SK', 'Slovakia', array['Slovakia']),
  ('SL', 'Sierra Leone', array['Sierra Leone']),
  ('SM', 'San Marino', array['San Marino']),
  ('SN', 'Senegal', array['Senegal']),
  ('SO', 'Somalia', array['Somalia']),
  ('SR', 'Suriname', array['Suriname']),
  ('SS', 'South Sudan', array['South Sudan']),
  ('ST', 'Sao Tome and Principe', array['Sao Tome and Principe']),
  ('SV', 'El Salvador', array['El Salvador']),
  ('SX', 'Sint Maarten (Dutch part)', array['Sint Maarten (Dutch part)']),
  ('SY', 'Syrian Arab Republic', array['Syrian Arab Republic']),
  ('SZ', 'Eswatini', array['Eswatini']),
  ('TC', 'Turks and Caicos Islands', array['Turks and Caicos Islands']),
  ('TD', 'Chad', array['Chad']),
  ('TF', 'French Southern Territories', array['French Southern Territories']),
  ('TG', 'Togo', array['Togo']),
  ('TH', 'Thailand', array['Thailand']),
  ('TJ', 'Tajikistan', array['Tajikistan']),
  ('TK', 'Tokelau', array['Tokelau']),
  ('TL', 'Timor-Leste', array['Timor-Leste']),
  ('TM', 'Turkmenistan', array['Turkmenistan']),
  ('TN', 'Tunisia', array['Tunisia']),
  ('TO', 'Tonga', array['Tonga']),
  ('TR', 'Türkiye', array['Türkiye', 'Turkey']),
  ('TT', 'Trinidad and Tobago', array['Trinidad and Tobago']),
  ('TV', 'Tuvalu', array['Tuvalu']),
  ('TW', 'Taiwan, Province of China', array['Taiwan, Province of China', 'Taiwan']),
  ('TZ', 'United Republic of Tanzania', array['United Republic of Tanzania', 'Tanzania']),
  ('UA', 'Ukraine', array['Ukraine']),
  ('UG', 'Uganda', array['Uganda']),
  ('UM', 'United States Minor Outlying Islands', array['United States Minor Outlying Islands']),
  ('US', 'United States of America', array['United States of America', 'United States', 'USA', 'U.S.A.', 'US', 'U.S.']),
  ('UY', 'Uruguay', array['Uruguay']),
  ('UZ', 'Uzbekistan', array['Uzbekistan']),
  ('VA', 'Holy See (Vatican City State)', array['Holy See (Vatican City State)']),
  ('VC', 'Saint Vincent and the Grenadines', array['Saint Vincent and the Grenadines']),
  ('VE', 'Venezuela', array['Venezuela']),
  ('VG', 'Virgin Islands, British', array['Virgin Islands, British']),
  ('VI', 'Virgin Islands, U.S.', array['Virgin Islands, U.S.']),
  ('VN', 'Vietnam', array['Vietnam']),
  ('VU', 'Vanuatu', array['Vanuatu']),
  ('WF', 'Wallis and Futuna', array['Wallis and Futuna']),
  ('WS', 'Samoa', array['Samoa']),
  ('XK', 'Kosovo', array['Kosovo']),
  ('YE', 'Yemen', array['Yemen']),
  ('YT', 'Mayotte', array['Mayotte']),
  ('ZA', 'South Africa', array['South Africa']),
  ('ZM', 'Zambia', array['Zambia']),
  ('ZW', 'Zimbabwe', array['Zimbabwe']);

-- No index. The table is 250 rows that never grow, and the lookup below runs
-- once per document insert; a sequential scan over 250 rows is cheaper than the
-- index it would have to maintain.

-- Reference data: every signed-in user reads it, nobody writes it. There is no
-- org_id here, so the member test that guards every tenant table does not
-- apply — being authenticated is the whole check.
alter table public.country_codes enable row level security;
alter table public.country_codes force  row level security;

create policy country_codes_select on country_codes for select to authenticated using (true);
-- No insert/update/delete policy: the list changes when ISO changes it, which
-- means regenerating this file, not writing from the browser.

revoke all on public.country_codes from anon;
revoke insert, update, delete on public.country_codes from authenticated;

-- Resolve whatever a human typed into a code. Returns null when nothing
-- matches, which callers treat as "country unknown" rather than as an error.
create or replace function app.country_code_from_name(p_name text)
returns char(2) language sql stable as $fn$
  select c.code
    from public.country_codes c
   where p_name is not null
     and btrim(p_name) <> ''
     and (
       lower(btrim(p_name)) = lower(c.name)
       or lower(btrim(p_name)) = lower(c.code)
       or exists (
         select 1 from unnest(c.aliases) a
          where lower(a) = lower(btrim(p_name))
       )
     )
   limit 1;
$fn$;
